### PR TITLE
Websocket implementation

### PR DESCRIPTION
**Pull request by huynhminhtufu**
Specs referrence [socket.io](https://socket.io/docs/server-api/) - (APIs inspired from socket.io)

Dependency: 'org.java-websocket'

(Under the hood it uses a `java.nio` Java1.4 SE API, resulting in high throughput WebSocket server)
**Tested on VM: CentOS, 4vCPU, 2GB RAM, Java 8**
**Client Sessions**:

- 50,000 WebSocket sessions on single node

**TPS**:

- 4,000 requests per second per single channel
- 80,000 requests per second total

Sample usage server:

```java
import com.jinyframework.websocket.WebSocketServer;
import com.jinyframework.websocket.server.Socket;
import lombok.val;

import java.util.concurrent.ThreadLocalRandom;

public class Main {
    public static void main(String[] args) {
        val io = WebSocketServer.port(1234);

        // Return socket identify string or throw error
        io.handshake(req -> {
            val randomId = ThreadLocalRandom.current().nextInt();
            return "guess" + randomId;
        });

        io.onOpen(socket ->
                System.out.println("New connection: " + socket.getIdentify()));
        io.onClose((socket, code, reason) ->
                System.out.println("Closed connection: " + socket.getIdentify() + ", code: " + code + ", reason: " + reason));
        io.onError((socket, ex) ->
                System.out.println("Socket error: " + socket.getIdentify() + ", error: " + ex.getMessage()));

        io.on("ping", (socket, message) -> {
            socket.emit("pong");
        });

        io.on("room/join", Socket::join); // Join room
        io.on("room/leave", Socket::leave); // Leave room

        // Global chat
        io.on("chat/global", (socket, message) ->
                io.emit("chat/global", socket.getIdentify(), message));

        // Receive room chat message
        io.on("chat/private", (socket, message) -> {
            val messageArray = message.split(":");
            val roomName = messageArray[0];
            val messageData = message.replaceFirst(roomName + ":", "");
            io.emitRoom(roomName,
                    "room-chat",
                    roomName, socket.getIdentify(), messageData);
        });

        io.start();
    }
}
```

Sample usage client:

```java
val client = WebSocketClient.builder()
        .uri("ws://localhost:1234")
        .build().connect();

client.on("chat/global", message -> {
    System.out.println("New global chat: " + message);
});

client.on("pong", message -> {
    System.out.println("Pong: " + message);
});

client.emit("chat/global", "Hello World");
client.emit("ping", "Ping message");
```

### CODE REVIEW

**Review by mocmeo — DISMISSED** [review]
LGTM

**Review by mocmeo — APPROVED** [review]
LGTM part 2

**Review by huynhducduy — APPROVED** [review]
私にはよく見えますよ。

**Review by axblueblader — APPROVED** [review]
LGTM

**Pull request merged**
