### PR TITLE
Feature: Refactor custom data (Object) support in Context

### LINKED ISSUE #24: A storage for custom data to pass along the handler chain
Problem:
- I'm currently working on JWT middleware and realized that there is no place to store custom data in Context object so the middleware can't pass on user info after token verification to other handlers in the chain.

Proposal:
- Have HashMap in Context object for storing custom data that are meant to pass along the chain. Other frameworks usually use something like ```ctx.Put("Key",valueObject)```

### PR DESCRIPTION
**Pull request by axblueblader**
Should fix #24

### CODE REVIEW

**Comment by huynhminhtufu** [comment]
@axblueblader Please try to add more tests using another type of Object such as HashMap or ArayList

**Comment by axblueblader** [comment]
> @axblueblader Please try to add more tests using another type of Object such as HashMap or ArayList

ok I will, also what format style are you using, my auto import keeps messing with the ordering due to different style settings

**Comment by huynhminhtufu** [comment]
@axblueblader IntelliJ's reformat feature, use it before commit, I'm also looking for a real "linter" that could be use to test code style during CI

**Review by huynhminhtufu — APPROVED** [review]
LGTM

**Review by ldhnam — APPROVED** [review]
LGTM

**Pull request merged**
