### PR TITLE
[WIP] CORS middleware implementation

### PR DESCRIPTION
**Pull request by axblueblader**
Hi, I'm trying to implement CORS middleware according to [spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and using these 2 as references [rs/cors](https://github.com/rs/cors), [express/cors](https://github.com/expressjs/cors).
- [x] allow all and allow list of origins
- [x] other normal headers (credentials, expose headers)
- [x] preflight request handling
- [x] refactor to support sensible defaults

future enhancement:
- support wildcard origins
- customizable origin validation
- possibly logging?

### CODE REVIEW

**Comment by huynhminhtufu** [comment]
@axblueblader Please also bring an example code guide (how to use it) on the PR description, I will add to [docs](https://jinyframework.com/guide/basic/middlewares.html) too.

**Comment by axblueblader** [comment]
> @axblueblader Please also bring an example code guide (how to use it) on the PR description, I will add to [docs](https://jinyframework.com/guide/basic/middlewares.html) too.

Ok, I added an example file in test folders. How do you feel about the API btw? I fear that current implementation is not concise enough.

**Comment by huynhminhtufu** [comment]
@axblueblader LGTM, btw our target is not to make the **code as short as possible** (and increase the implicit just like Spring Boot, and this approach will make Jiny a 'reinventing-the-wheel' project) but **as expressive as possible**.

**Comment by huynhminhtufu** [comment]
@axblueblader  IHMO, It's better to add the example code in `/docs` or `/examples`, not in `src` dir to exclude it from the .jar library bundle file (thus it will not increase the .jar lib file size)

In case you want to test with the Main class, you can create a Gradle **sub-project** by:

```
mkdir testproject
cd testproject
touch build.gradle
```

My testproject's gradle file:

```groovy
plugins {
    id 'java'
    id 'idea'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '6.0.0'
}

group 'com.jinyframework'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.12'
    annotationProcessor 'org.projectlombok:lombok:1.18.12'

    compile project(':')

    compile group: 'com.google.code.gson', name: 'gson', version: '2.8.6'

    compile group: 'org.mongodb', name: 'mongodb-driver-sync', version: '4.1.0-beta2'
    compile group: 'com.github.jknack', name: 'handlebars', version: '4.2.0'

    compile group: 'mysql', name: 'mysql-connector-java', version: '5.1.49'
    compile group: 'org.hibernate', name: 'hibernate-core', version: '5.3.6.Final'

    compile "org.java-websocket:Java-WebSocket:1.5.1"

    compile group: 'ch.qos.logback', name:'logback-classic', version: '1.0.9'
    compile group: 'ch.qos.logback', name:'logback-core', version: '1.0.9'
}

application {
    mainClassName = 'com.jinyframework.examples.crud.Main'
}
```

Then add `src` packages and run `./gradlew testproject:run`.

I already added `testproject/` in the `.gitignore` and modified the `settings.gradle` to accept testproject as a sub project

**Comment by huynhminhtufu** [comment]
If you think there's a better way to do things or something is currently been misunderstood, please also let me know :)

**Comment by axblueblader** [comment]
@huynhminhtufu ok got it, thanks for guiding

**Comment by huynhminhtufu** [comment]
@axblueblader Merged with new subProject structured, please check

**Comment by axblueblader** [comment]
Some example code
```java
        final HttpServer server = HttpServer.port(1234);
        server.use("/default", Cors.newHandler(Cors.allowDefault()),
                   ctx -> HttpResponse.of("cors default settings"));
        server.use("/all", Cors.newHandler(Cors.allowAll()),
                   ctx -> HttpResponse.of("cors enabled for all"));

        final Config defaultBased = Config.defaultBuilder()
                                          .allowOrigin("*")
                                          .exposeHeader("Bar")
                                          .build();
        server.use("/extend-default", Cors.newHandler(defaultBased),
                   ctx -> HttpResponse.of("extend from default settings"));

        final List<String> allowMethods = Stream.of("GET", "POST", "HEAD", "PUT").collect(Collectors.toList());
        final List<String> allowHeaders = Stream.of("Origin", "Accept", "Content-Type", "X-Requested-With",
                                                    "Bar").collect(Collectors.toList());
        final Config allowConsole = Config.builder()
                                          .allowAllOrigins(false)
                                          .allowCredentials(true)
                                          .allowOrigin("http://localhost:8080")
                                          .exposeHeader("Foo")
                                          .allowMethods(allowMethods)
                                          .allowHeaders(allowHeaders)
                                          .build();
        server.use("/console",
                   Cors.newHandler(allowConsole),
                   ctx -> HttpResponse.of("google chrome console"));
```

**Review by huynhminhtufu — APPROVED** [review]
LGTM

**Pull request merged**
